$terminal = ghostty
$files = nautilus
$audio = pavucontrol
$browser = flatpak run app.zen_browser.zen
$music = flatpak run com.spotify.Client
$clipboard = clipse -listen
$code = zeditor
$quickshell = qs -p ~/.config/quickshell

$blender = ~/Apps/Blender/blender
$godot = ~/Apps/Godot/godot
