#######################
### Hyprland Config ###
#######################

# PATHS
$hl = ~/.config/hypr/hyprland

# CONFIGS
source = $hl/animations.conf
source = $hl/apps.conf
source = $hl/autostart.conf
source = $hl/colors.conf
source = $hl/cursor.conf
source = $hl/decoration.conf
source = $hl/env.conf
source = $hl/group.conf
source = $hl/input.conf
source = $hl/keybinds.conf
source = $hl/misc.conf
source = $hl/monitors.conf
source = $hl/rules.conf

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 4
    gaps_out = 4, 0, 0, 0

    border_size = 2

	col.active_border = $white
    col.inactive_border = $grey

    resize_on_border = false
    allow_tearing = false

    layout = dwindle

	snap {
		enabled = true
	}
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = false # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
	new_status = master
}

ecosystem {
    no_update_news = false
    no_donation_nag = false
}
