{ pkgs, unstablePkgs, ... }:
{
  fonts.packages = [
    pkgs.adwaita-fonts
    pkgs.noto-fonts
    pkgs.noto-fonts-cjk-sans
    pkgs.noto-fonts-color-emoji
    pkgs.font-awesome
    pkgs.nerd-fonts.jetbrains-mono
    pkgs.nerd-fonts.symbols-only
  ];

  environment.systemPackages = [
    pkgs.adwaita-icon-theme
    pkgs.apostrophe
    pkgs.arduino-ide
    pkgs.audacity
    pkgs.blueman
    pkgs.bluez
    pkgs.brightnessctl
    pkgs.celluloid
    unstablePkgs.claude-code
    pkgs.kdePackages.breeze-icons
    pkgs.kdePackages.breeze
    pkgs.clipse
    pkgs.curl
    pkgs.ddcutil
    pkgs.decibels
    pkgs.dnsmasq
    pkgs.ffmpeg-full
    pkgs.file-roller
    pkgs.ghostty
    pkgs.gimp
    pkgs.git
    pkgs.glib
    pkgs.grim
    pkgs.hicolor-icon-theme
    pkgs.htop
    unstablePkgs.hyprcursor
    unstablePkgs.hypridle
    unstablePkgs.hyprlang
    unstablePkgs.hyprpaper
    unstablePkgs.hyprpicker
    unstablePkgs.hyprpolkitagent
    unstablePkgs.hyprshot
    unstablePkgs.hyprsunset
    unstablePkgs.hyprsysteminfo
    unstablePkgs.hyprutils
    unstablePkgs.hyprwayland-scanner
    unstablePkgs.hyprwire
    unstablePkgs.hyprgraphics
    unstablePkgs.hyprland-qt-support
    unstablePkgs.hyprland-qtutils
    unstablePkgs.hyprnotify
    pkgs.iftop
    pkgs.imagemagick
    pkgs.inkscape
    pkgs.iw
    pkgs.iwd
    pkgs.jq
    pkgs.libnotify
    pkgs.lsof
    pkgs.loupe
    pkgs.man-db
    pkgs.meson
    pkgs.mpv
    pkgs.nautilus
    pkgs.neovim
    pkgs.nix
    pkgs.nil
    pkgs.nixd
    pkgs.nmap
    pkgs.papers
    pkgs.pavucontrol
    pkgs.playerctl
    pkgs.power-profiles-daemon
    pkgs.psmisc
    pkgs.pureref
    pkgs.quickshell
    pkgs.showtime
    pkgs.slurp
    pkgs.tmux
    pkgs.util-linux
    pkgs.usb-modeswitch
    pkgs.vim
    pkgs.wget
    pkgs.which
    pkgs.wl-clipboard
    pkgs.zed-editor
  ];
}
