#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

#Cursor
#env = HYPRCURSOR_THEME,Adwaita
#env = HYPRCURSOR_SIZE,28
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,22

# Flatpak
# Put cursors in /usr/share/icons and ~/.icons
# Put themes in /usr/share/themes and ~/.themes
#exec = flatpak override --filesystem=~/.themes:ro --filesystem=~/.icons:ro --user

# QT
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
#env = QT_IM_MODULE,fcitx5

# GTK
exec = ~/.config/hypr/scripts/configure/gtk.sh
#env = GTK_IM_MODULE,fcitx5

# Nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = LIBVA_DRIVER_NAME,nvidia

# General
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
