local pacman_pkgs = {
  applications = {
    "flatpak",
    "ghostty",
    "htop",
    "inkscape",
    "loupe",
    "mako",
    "nautilus",
    "neovim",
    "quickshell",
    "spotify-launcher",
    "tmux",
    "vim",
    "waybar",
    "wofi",
    "zed",
  },
  fonts = {
    "adwaita-fonts",
    "noto-fonts",
    "noto-fonts-cjk",
    "noto-fonts-emoji",
    "otf-font-awesome",
    "ttf-nerd-fonts-symbols",
    "ttf-noto-nerd",
  },
  hyprland = {
    "hyprcursor",
    "hyprgraphics",
    "hypridle",
    "hyprland",
    "hyprland-protocols",
    "hyprland-qt-support",
    "hyprland-guiutils",
    "hyprlang",
    "hyprlock",
    "hyprpaper",
    "hyprpicker",
    "hyprpolkitagent",
    "hyprshot",
    "hyprshutdown",
    "hyprsunset",
    "hyprtoolkit",
    "hyprutils",
    "hyprwayland-scanner",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland",
  },
  im = {
    "fcitx5",
    "fcitx5-gtk",
    "fcitx5-qt",
    "fcitx5-mozc",
    "fcitx5-configtool",
  },
  programming = {
    "clang",
    "cmake",
    "git",
    "go",
    "meson",
    "ninja",
    "npm",
    "nodejs",
    "pyright",
    "python",
    "rust",
    "rust-analyzer",
    "rust-src",
  },
  themes = {
    "adwaita-icon-theme",
    "adwaita-cursors",
    "breeze-icons",
    "breeze-gtk",
    "breeze-cursors",
    "hicolor-icon-theme",
  },
  utility = {
    "blueman",
    "bluez",
    "bluez-utils",
    "brightnessctl",
    "cups",
    "curl",
    "dnsmasq",
    "iw",
    "iwd",
    "man-db",
    "modemmanager",
    "network-manager-applet",
    "nm-connection-editor",
    "pavucontrol",
    "pipewire",
    "playerctl",
    "qt6ct",
    "usb_modeswitch",
    "wayland",
    "wayland-docs",
    "wayland-protocols",
    "wayland-utils",
    "wcurl",
    "websocat",
    "wget",
    "which",
    "wireplumber",
    "wl-clipboard",
  },
}

local aur_pkgs = {
  "yay",
  "clipse",
  "hyprlauncher",
}

local flatpak_pkgs = {
  "app.zen_browser.zen",
  "com.obsproject.Studio",
  "com.discordapp.Discord",
}

return {
  pacman_pkgs = pacman_pkgs,
  aur_pkgs = aur_pkgs,
  flatpak_pkgs = flatpak_pkgs,
}
